### ISSUE TITLE
When i try to run the application, I got some problem. 

### ISSUE THREAD

**Issue by s1014023** [priyanka-badgujar/Android-Maps#1]
2020-05-11 20:37:40.208 4340-4426/com.example.locationbasedalarm E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.example.locationbasedalarm, PID: 4340
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:200)
        at android.os.Handler.<init>(Handler.java:114)
        at android.app.Dialog.<init>(Dialog.java:122)
        at android.app.Dialog.<init>(Dialog.java:167)
        at androidx.appcompat.app.AppCompatDialog.<init>(AppCompatDialog.java:57)
        at androidx.appcompat.app.AlertDialog.<init>(AlertDialog.java:98)
        at androidx.appcompat.app.AlertDialog$Builder.create(AlertDialog.java:981)
        at com.example.locationbasedalarm.MapsActivity.showErrorMsg(MapsActivity.java:546)
        at com.example.locationbasedalarm.MapsActivity$DownloadTask.doInBackground(MapsActivity.java:337)
        at com.example.locationbasedalarm.MapsActivity$DownloadTask.doInBackground(MapsActivity.java:329)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 

After i enter and press the place name, the app was stopped.

**Comment by priyanka-badgujar** [comment]
Please check your internet connection and your device location must be on. Let me know if this works for you

**Comment by s1014023** [comment]
![cap](https://user-images.githubusercontent.com/58317157/81570251-ed304400-93d2-11ea-815e-c21843a6df71.png)
All work of the application.
But when i enter the name and press it, it will stop.
![cap2](https://user-images.githubusercontent.com/58317157/81570414-24065a00-93d3-11ea-87ab-10530df7064a.png)

**Comment by priyanka-badgujar** [comment]
This is working fine for me. I am not sure why this is not working for you. Try to enter nearby locations. This could be because of out of bound location...

**Comment by s1014023** [comment]
Even i enter 5m building address, it also not working.
Anyway, thank you for your help.
